### ISSUE TITLE
Files are missing from repository, cannot rebuild project in 4.22.3.

### ISSUE THREAD

**Issue by SnarfDev** [CGJiaxiLiu/MyPortfolio#1]
Missing specifically are Source\JoyconInputPlugin\Bin and
Source\JoyconInputPlugin\Lib.

This has been failed multiple times. I have built with unreal engines rebuilder and Visual Studio. I am unaware of other ways to use this plugin. If you have the time, please add the files to the repository or if I have done something wrong I would like to know that as well. Cheers.

**Comment by CGJiaxiLiu** [comment]
Yes, the referenced .lib and .dll were ignored, I have added the missing library. Thank you for pointing out! If the building issues still exists, please don't hesitate to tell me and I will have a thorough test.

**Comment by SnarfDev** [comment]
Thank you! Everything appears to be working now, thank you for the quick response. Very nice plugin, good work.
